easy_admin:
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        User:
            class: App\Entity\User
            list:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'username'
                    - { property: 'roles', template: 'admin/user/roles-type-read.html.twig' }
                    - { property: 'homepage', type: 'url' }
                    - { property: 'password', template: 'admin/user/password-read.html.twig' }
            form:
                fields:
                    - { property: 'email', type: 'email' }
                    - { property: 'roles', type: 'collection' }
                    - { property: 'plainPassword', type: 'password' }
                    - { property: 'homepage', type: 'url' }

    user:
        name_property_path: "email"